<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findLatest($count = 5) {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('c')
            ->from('AppBundle:Comment', 'c')
            ->where('c.flag = :flag')
            ->orderBy('c.id')
            ->setParameter('flag', 1)
            ->setMaxResults($count);

        return $qb->getQuery()->getResult();

    }

}
