root:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_other:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
