
root:
    path: /
    defaults: { _controller: AppBundle:Home:index }

site_details:
    path: /sites/{url}
    defaults: { _controller: AppBundle:Site:details}

search_results:
    path:     /search
    defaults: { _controller: AppBundle:Search:search }

avatara_image:
    path:     /avatara/{id}
    defaults: { _controller: AppBundle:User:avatara}

# auth routs
login:
    path:     /login
    defaults: { _controller: AppBundle:Facebook:connect }

facebook_check:
    path:     /facebook_check
    defaults: { _controller: AppBundle:Facebook:connectCheck }

profile:
    path:   /profile
    defaults: { _controller: AppBundle:User:profile }

logout:
    path:   /logout
