
root:
    path: /
    defaults: { _controller: AppBundle:Home:index }

connect:
    path:     /login
    defaults: { _controller: AppBundle:Facebook:connect }

facebook_check:
    path:     /facebook_check
    defaults: { _controller: AppBundle:Facebook:connectCheck }

profile:
    path:   /profile
    defaults: { _controller: AppBundle:User:profile }

logout:
    path:   /logout
