AppBundle\Entity\Review:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ReviewRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        rating:
            type: smallint
        title:
            type: string
            length: '255'
        review:
            type: text
        dateCreated:
            type: datetime
            column: date_created
    lifecycleCallbacks: {  }

    manyToOne:
        user:
            targetEntity: User
