AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
        email:
            type: string
            length: 100
            unique: true
        avatara:
            type: blob
            nullable: true
        facebookId:
            type: string
            length: 100
            nullable: true
            unique: true
        apiKey:
            type: string
            length: 255
            nullable: true
            unique: true
        roles:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks: {  }
